pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    app base User class

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s" % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

pypro/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

pypro/base/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>RazorWolf</title>
    <meta name="description" content=" Venha para nossa barbearia e saia com um corte de cabelo impecável.">
    <meta name="author" content="Pedro Lopes">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" />
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/scripts.js"></script>
</head>
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: 0;
    }

    body {
        width: 100vw;
        height: 100vh;
        background-image: url({% static 'img/tmj.jpeg'%});

    }
</style>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'base:home' %}">RazorWolf</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                                data-toggle="dropdown">Dropdown link</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another
                                    action</a> <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider">
                                </div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-inline">
                        <input class="form-control mr-sm-2" type="text">
                        <button class="btn btn-primary my-2 my-sm-0" type="submit">
                            Search
                        </button>
                    </form>
                    <ul class="navbar-nav ml-md-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                                data-toggle="dropdown">Dropdown link</a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another
                                    action</a> <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider">
                                </div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                </div>
                </nav>
                <div class="jumbotron">
                    <h2>
                        Estilo e precisão A arte da barbearia Pedro Lopes
                    </h2>
                    <p>
                        Está na hora de dar um trato no visual! Venha para nossa barbearia e saia com um corte de cabelo
                        impecáve
                        <a href="https://www.facebook.com/search/top?q=pedro%20lopes" target="_blank">RazorWolf</a>
                    <h4 class="mt-4"> CORTE R$ 50,00</h4>
                    <h4 class="mt-4"> BARBA R$ 30,00</h4>
                    <h4 class="mt-4"> SOBRANCELHA R$ 20,00</h4>
                    <h4 class="mt-4"> NEVOU R$ 100,00</h4>
                    <h4 class="mt-4"> PEZINHO R$ 15,00</h4>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-calendar2-day-fill" viewBox="0 0 16 16">
                        <path
                            d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5m9.954 3H2.545c-.3 0-.545.224-.545.5v1c0 .276.244.5.545.5h10.91c.3 0 .545-.224.545-.5v-1c0-.276-.244-.5-.546-.5m-2.24 4.855a.428.428 0 1 0 0-.855.426.426 0 0 0-.429.43c0 .238.192.425.43.425zm.337.563h-.672v4.105h.672zm-6.867 4.105v-2.3h2.261v-.61H4.684V7.801h2.464v-.61H4v5.332zm3.296 0h.676V9.98c0-.554.227-1.007.953-1.007.125 0 .258.004.329.015v-.613a1.806 1.806 0 0 0-.254-.02c-.582 0-.891.32-1.012.567h-.02v-.504H7.98v4.105z" />
                    </svg>
                    <button type="button" class="btn btn-light"><a
                            href="https://calendly.com/davidsoncastro748razorwolf/30min" target="_blank">AGENDA SEU
                            HORARIO AQUI </a></button>

                    </p>
                    <p>
                    </p>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <h5 class="card-header">
                                Mais detalhes sobre a barbearia RazorWolf
                            </h5>
                            <div class="card-body">
                                <p class="card-text">
                                    <img src="{%static 'img/ppg.ico'%}" alt="Foto de Pedro Lopes"
                                        class="img-thumbnail float-left mr-3" />
                                    Um barbeiro é um profissional especializado em cortar e modelar cabelos,
                                    fazer barbas e cuidar da aparência masculina. Geralmente, eles trabalham em
                                    barbearias ou salões de beleza masculinos. A biografia de um barbeiro pode
                                    incluir sua formação em cursos específicos de barbearia, experiência de
                                    trabalho em diferentes estabelecimentos, habilidades e técnicas dominadas ao longo
                                    da carreira,
                                    além do seu estilo pessoal e abordagem no atendimento aos clientes
                                    <a href="https://www.facebook.com/search/top?q=pedro%20lopes"
                                        target="_blank">RazorWolf</a>

                                </p>

                            </div>
                        </div>
                    </div>
                    <footer class="footer mt-5 pt-4 text-light">
                        <div class="container">
                            <div class="row">
                                <div class="col">
                                    <h3>Entre em Contato</h3>
                                    <address>
                                        +351 925 898 822
                                        <br />
                                        <a href="mailtonpedrolopes123@hotmail.com"
                                            class="text-light">pedrolopes123@hotmial.com</a>
                                    </address>
                                </div>
                            </div>
                        </div>
                        <div class=" pb-4">
                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                        {% now 'Y' %} RazorWolf. Todos direitos reservados.
                                    </div>
                                </div>

                                <a href="https://wa.me/5531999877987" target="_blank"
                                    style="position:fixed;bottom:20px;right:30px;">
                                    <svg enable-background="new 0 0 512 512" width="50" height="50" version="1.1"
                                        viewBox="0 0 512 512" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M256.064,0h-0.128l0,0C114.784,0,0,114.816,0,256c0,56,18.048,107.904,48.736,150.048l-31.904,95.104  l98.4-31.456C155.712,496.512,204,512,256.064,512C397.216,512,512,397.152,512,256S397.216,0,256.064,0z"
                                            fill="#4CAF50" />
                                        <path
                                            d="m405.02 361.5c-6.176 17.44-30.688 31.904-50.24 36.128-13.376 2.848-30.848 5.12-89.664-19.264-75.232-31.168-123.68-107.62-127.46-112.58-3.616-4.96-30.4-40.48-30.4-77.216s18.656-54.624 26.176-62.304c6.176-6.304 16.384-9.184 26.176-9.184 3.168 0 6.016 0.16 8.576 0.288 7.52 0.32 11.296 0.768 16.256 12.64 6.176 14.88 21.216 51.616 23.008 55.392 1.824 3.776 3.648 8.896 1.088 13.856-2.4 5.12-4.512 7.392-8.288 11.744s-7.36 7.68-11.136 12.352c-3.456 4.064-7.36 8.416-3.008 15.936 4.352 7.36 19.392 31.904 41.536 51.616 28.576 25.44 51.744 33.568 60.032 37.024 6.176 2.56 13.536 1.952 18.048-2.848 5.728-6.176 12.8-16.416 20-26.496 5.12-7.232 11.584-8.128 18.368-5.568 6.912 2.4 43.488 20.48 51.008 24.224 7.52 3.776 12.48 5.568 14.304 8.736 1.792 3.168 1.792 18.048-4.384 35.52z"
                                            fill="#FAFAFA" />
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </footer>